### ISSUE TITLE
bin/line2lambdacloud didn't count the transfer num last time

### ISSUE THREAD

**Issue by GodHong** [lambdacloud/lambda-util.js#21]
As follow:
$: cat /data/lambdacloudlog.bak | bin/line2lambdacloud --token *****\* &
[3] 11494
  uploading...  total: 22656 success: 17728 timeout: 0 retries: 0 duration: in a few seconds
LambdaCloud uploading stats: {"total":23710,"success":19968,"timeout":0,"retries":0,"lastTimestamp":"2015-07-30T02:53:36.470Z","lastMessage":"日志类型[生产部队完成],时间[...","error":{}}

**Comment by wezhang** [comment]
在bulk传输时加入了定时器来传送最后一次的数据。
